apiVersion: v1
kind: Service
metadata:
  name: nba-memes-service
  labels:
    app: nba-memes
spec:
  selector:
    app: nba-memes      # Selects pods with this label so it must match pod labels
  ports:
    - protocol: TCP
      port: 80          # Cluster-internal port
      targetPort: 80    # Container port
  type: NodePort        # # Exposes service outside cluster via node port || change to LoadBalancer if running in cloud

